#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;
use Symfony\Component\Lock\Factory;
use Symfony\Component\Lock\Store\FlockStore;

require_once __DIR__ . '/vendor/autoload.php';

require_once __DIR__ . '/CalculateFibonacciCommand.php';
require_once __DIR__ . '/CheckIsPrimeCommand.php';

$console = new Application();

$console->add(
    new CalculateFibonacciCommand(
        new Factory(new FlockStore()),
        'fib'
    )
);
$console->add(
    new CheckIsPrimeCommand('is-prime')
);

$console->run();
